<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ArticuloDetalle.aspx.cs" Inherits="SFDBK_Web_Estable.Views.Catalago.ArticuloDetalle" %>
<%@ Register assembly="DevExpress.Web.v17.2, Version=17.2.5.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" namespace="DevExpress.Web" tagprefix="dx" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <br />
    <asp:Panel runat="server" Width="100%" Height="550px" BackColor="LightGray">
        <table>
            <tr>
                <td rowspan="2">
                    <dx:ASPxImageSlider ID="ASPxImageSlider1" runat="server" ImageSourceFolder="~/Images">
                        <SettingsAutoGeneratedImages ImageCacheFolder="~/Thumb/"/>
                    </dx:ASPxImageSlider>
                </td>
                <td>
                    <label>Codigo: </label>
                    <asp:Label runat="server" ID="lblCodigo">N° codigo</asp:Label>
                    <br />
                    <label>Disponibilidad: </label>
                    <asp:Label runat="server" ID="lblDisponibles">N° disponibles</asp:Label>
                    <br />
                    <br />
                    <h1>
                        <asp:Label runat="server" ID="lblDescripcion">Torres para auto 2 toneladas Mikels</asp:Label>
                    </h1>
                    <br />
                    <h1><asp:Label runat="server" ID="lblPrecio" ForeColor="Green">$350.00</asp:Label></h1>
                    <br />
                    <H2>
                        <label>Cantidad: </label>
                        <asp:TextBox runat="server" ID="txtCantidad" Width="50px"></asp:TextBox>
                        <br />
                        <br />
                        <center>
                            <asp:Button runat="server" Text="Agregar al carrito" ID="btnAddCarrito" />
                        </center>
                        
                    </H2>
                    
                </td>
            </tr>

        </table>
        

    </asp:Panel>
</asp:Content>
